[package]
name = "eTamil"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = "0.4"
antlr-rust = { git = "https://github.com/rrevenantt/antlr4rust.git", rev = "360bc024" }


[build-dependencies]
antlr-rust = { git = "https://github.com/rrevenantt/antlr4rust.git" }
